### ISSUE TITLE
Upload district layers to MapBox

### ISSUE THREAD

**Issue by danmillr** [CEANYC/directory-map#102]
As tilesets, with tileset ID

City Council: ceanyc.61d7smpp
Community Districts: ceanyc.43nv7pgw
ZIP Codes: ceanyc.4z7ruq9j

**Comment by danmillr** [comment]
@ebrelsford I just quickly uploaded these as tilesets in MapBox Studio, but can edit fields and style in studio if need be. Are there some other updates that would be helpful in integrating them?

**Comment by ebrelsford** [comment]
That should work fine @danmillr, are they also in the Mapbox Studio style in #67? Ideally they would be to make it easier to turn them on and off.

**Comment by danmillr** [comment]
Hi @ebrelsford I just added them all, with outlines and labels to the style and published it. 

<img width="234" alt="Screen Shot 2022-09-08 at 5 51 00 PM" src="https://user-images.githubusercontent.com/16843924/189232515-aff5e263-5423-4f68-8fa3-b972be8f7b08.png">

Do you have any suggestions on how I  should configure them (hide?) by default in the style to work with the toggle?

**Comment by danmillr** [comment]
<img width="293" alt="Screen Shot 2022-09-08 at 5 54 00 PM" src="https://user-images.githubusercontent.com/16843924/189232706-a4b9e6ef-e4b1-44dc-a831-70b9272b08e7.png">
