### ISSUE TITLE
Create a favicon

### ISSUE THREAD

**Issue by ebrelsford** [CEANYC/directory-map#107]
@danmillr is this something you could create? It's the default nuxt favicon for now:

![Image](https://user-images.githubusercontent.com/375002/190535961-ecb26741-a282-4633-8a34-02afd6e015c8.png)

**Comment by danmillr** [comment]
![Image](https://user-images.githubusercontent.com/16843924/191395942-67177f60-23f8-4720-ae27-9962fcee8550.svg)
@ebrelsford just generated this option, what do you think?

**Comment by ebrelsford** [comment]
works for me!
