### ISSUE TITLE
Integrate text blocks for about and contributors to info window

### ISSUE THREAD

**Issue by danmillr** [CEANYC/directory-map#115]

**Comment by danmillr** [comment]
![Image](https://user-images.githubusercontent.com/16843924/191888499-2a190f79-d259-488e-8be4-6d6fdeb9157c.png)

@ebrelsford adding this example of how the text blocks could be integrated into the info window. I edited the text slightly to match in the airtable base

**Comment by ebrelsford** [comment]
@danmillr Done!
