### ISSUE TITLE
Configure Read Only Airtable API

### ISSUE THREAD

**Issue by danmillr** [CEANYC/directory-map#59]

**Comment by danmillr** [comment]
https://support.airtable.com/hc/en-us/articles/360056249614-Creating-a-read-only-API-key

**Comment by ebrelsford** [comment]
Still seems like we need a new account with read-only access to the base right?

**Comment by danmillr** [comment]
Set up a read-only account with this key: key2ohFyZoWJ8Hp9q

**Comment by ebrelsford** [comment]
@danmillr Did anything else about the Airtable access change? Did the database ID change? This key isn't working for me.

**Comment by danmillr** [comment]
@ebrelsford  I think the database ID changed when Ali set up the Pro account. 
https://airtable.com/appVbmRHpF0PZbybE/api/docs

**Comment by ebrelsford** [comment]
Okay that seems to be working.
