### ISSUE TITLE
Explore options for hosting images

### ISSUE THREAD

**Issue by danmillr** [CEANYC/directory-map#64]

**Comment by ebrelsford** [comment]
@danmillr What if we stored the images in Airtable as [attachments](https://support.airtable.com/hc/en-us/articles/360007852173-Attachment-field) then copied them over to the site using a GitHub Action? I can try the latter part if you want to add an attachment field to the sectors table and add an example image.

**Comment by ebrelsford** [comment]
Looking at the sectors table, looks like you already added an attachments field, so if we can add some test content there I can test it out.

**Comment by ebrelsford** [comment]
Actually nevermind, looking like we can just do this straight from Airtable--great!
