### ISSUE TITLE
Export icons

### ISSUE THREAD

**Issue by danmillr** [CEANYC/directory-map#68]
Set up a frame with design assets,  one with icons for export and integration into map

**Comment by danmillr** [comment]
Add to figma frame with descriptive IDs
https://stamen.com/figmasset-reducing-design-friction-while-making-map-markers-ea2d90cb061d/

**Comment by danmillr** [comment]
@ebrelsford I set up a page in our figma project and filled a frame with map markers: https://www.figma.com/file/QKak26OU1sGi0GzOHNtJPC/Sketch?node-id=349%3A528

I also added an option for selected markers that has a slightly darker stroke -- let me know what you think!

**Comment by ebrelsford** [comment]
Looking good so far!

![image](https://user-images.githubusercontent.com/375002/182999148-5ff34e84-870c-4c34-84aa-1dbee92944ec.png)
