### ISSUE TITLE
Hosting images on Airtable

### ISSUE THREAD

**Issue by danmillr** [CEANYC/directory-map#74]

**Comment by ebrelsford** [comment]
Double check that there aren't restrictions there.

**Comment by ebrelsford** [comment]
They are changing [how attachment URLs work](https://community.airtable.com/t/airtable-dropping-support-for-public-attachments/47539?page=2)--the URLs will expire after a few hours, but since we get the URL on page load that will be fine. Our app won't mind the URLs changing.
