### ISSUE TITLE
Select state for icons

### ISSUE THREAD

**Issue by danmillr** [CEANYC/directory-map#75]

**Comment by danmillr** [comment]
related to #68

**Comment by danmillr** [comment]
@ebrelsford do that existing options for icons on figma satisfy this? 
<img width="677" alt="image" src="https://user-images.githubusercontent.com/16843924/189741711-eee670fc-4a69-4e09-a541-dfc3c15b7aff.png">

**Comment by ebrelsford** [comment]
Yep I think we're good here!
